create database customer_behavior;
use customer_behavior;
select * from shop;

#1 What is the total revenue generated by male vs female customer
select gender,sum(purchase_amount) as revenue from shop group by gender;

# Which customers used a discount but still spent more than the average purchase amount
SELECT 
    customer_id, purchase_amount
FROM
    shop
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (select AVG(purchase_amount) from shop);
        
select * from shop;

#3 which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, round(AVG(review_rating),2) AS avg_rating
FROM
    shop
GROUP BY item_purchased
ORDER BY avg_rating desc
LIMIT 5;

#4 Compare the average purchase amount between standard and express shipping
SELECT 
    shipping_type, round(AVG(purchase_amount),2) AS avg_purchase
FROM
    shop
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

#5 Do subscribe customers spend more? Compare average spend and total revenue between subscribers and non-subscribed
select * from shop;
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customer,
    ROUND(AVG(purchase_amount), 2) AS avg_amount,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    shop
GROUP BY subscription_status;

# 6 Which 5 products have the highest percentage of purchases with discount applied
SELECT 
    item_purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*) * 100,
            2) AS discount_rate
FROM
    shop
GROUP BY item_purchased
order by discount_rate desc
limit 5;

/* 7. Segment customers fall into the "New," "Returning," and "Loyal"  based on their total number of previous purchases,
 and also show the count of each segment.*/
 select * from shop;
 with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from shop
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;
 
 
# 8. What are the top 3 most purchased products within each specific category?
select * from shop;
with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from shop
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;


# 9. Are repeat buyers (more than 5 previous purchases) likely to be subscribers?
select * from shop;
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    shop
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

# 10. What is the total revenue contribution of each age group (Young Adult, Adult, Middle-Aged, Senior)?
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    shop
GROUP BY age_group
ORDER BY total_revenue DESC;
